### ISSUE TITLE
PHP version support

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProjetPP/WikibaseEntityStore#3]
I'm curious why you are supporting PHP 5.3, which itself is no longer supported since last year.

http://blog.ircmaxell.com/2014/12/on-php-version-requirements.html

I'd go with requiring 5.5 or later. And I figured you are actually in a position where you can do this (the Wikidata team unfortunately is not).

**Comment by Tpt** [comment]
Yes, you have right. We should definitively switch to 5.5+

I'm so used of PHP 5.3+ (because of MediaWiki...) that I haven't thought at the beginning of the project to do 5.5+.

**Comment by Tpt** [comment]
Version 0.2 have switched to PHP 5.5+.

I have opened issue #12 about PHP 7 support.

**Comment by JeroenDeDauw** [comment]
\o/
