### ISSUE TITLE
VersionEye link broken

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProjetPP/WikibaseEntityStore#7]
It links to a user project, which can only be seen by the user in question. Log out and click the badge to see what I mean.

Link should be something like https://www.versioneye.com/php/ppp:wikibase-entity-store/dev-master

Oddly enough that currently does not show any dependencies, even though the project definitely has a few. @reiz any idea why that is?

**Comment by JeroenDeDauw** [comment]
Same issue applies to other PHP repos in this org

**Comment by reiz** [comment]
Currently debugging it!

**Comment by reiz** [comment]
@JeroenDeDauw The problem is that there are no tags on the repository! The 3 versions on packagist are branches and we stopped tracking branches. Still not sure if should be make an exception for dev-master.

**Comment by JeroenDeDauw** [comment]
@reiz dev-master is what packagist itself uses, so it's kinda odd for you to not use it

**Comment by reiz** [comment]
@JeroenDeDauw OK. I just updated the crawler. We still don't track branches! But we make an exception for dev-master. All other branches are still skipped at VersionEye. 

Here is the updated page: https://www.versioneye.com/php/ppp:wikibase-entity-store/dev-master

**Comment by Tpt** [comment]
Thank you very much!

**Comment by JeroenDeDauw** [comment]
@reiz awesome
